[package]
authors = ["Marcin S. <scatman@bu.edu>"]
description = "OVER: the best data format."
documentation = "https://docs.rs/over"
license = "MIT"
keywords = ["config", "format", "minimal", "intuitive", "powerful"]
name = "over"
readme = "README.md"
repository = "https://github.com/m-cat/over"
version = "0.2.0"

[dependencies]
fraction = "0.3.6"
num = "0.1.40"
num-traits = "0.1.40"
