[package]
authors = ["Marcin S. <scatman@bu.edu>"]
description = "OVER: the best data format."
license = "MIT"
name = "over"
readme = "README.md"
repository = "https://github.com/m-cat/over"
version = "0.1.0"

[dependencies]
fraction = "0.3.6"
num = "0.1.40"
num-traits = "0.1.40"
