[package]
authors = ["Marcin S. <scatman@bu.edu>"]
description = "Overman's Awesome Thing"
license = "MIT"
name = "over"
readme = "README.md"
repository = "https://github.com/m-cat/over"
version = "0.1.0"

[dependencies]
fraction = "0.3.4"
num = "0.1"
num-traits = "0.1.37"
